// Map of states to their major cities
export const STATE_CITIES: Record<string, string[]> = {
  al: ['Birmingham', 'Montgomery', 'Mobile', 'Huntsville', 'Tuscaloosa'],
  ak: ['Anchorage', 'Fairbanks', 'Juneau', 'Sitka', 'Ketchikan'],
  az: ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Scottsdale'],
  ar: ['Little Rock', 'Fort Smith', 'Fayetteville', 'Springdale', 'Jonesboro'],
  ca: ['Los Angeles', 'San Francisco', 'San Diego', 'Sacramento', 'San Jose'],
  co: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood'],
  ct: ['Hartford', 'Bridgeport', 'New Haven', 'Stamford', 'Waterbury'],
  de: ['Wilmington', 'Dover', 'Newark', 'Middletown', 'Smyrna'],
  fl: ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Tallahassee'],
  ga: ['Atlanta', 'Savannah', 'Augusta', 'Athens', 'Macon'],
  hi: ['Honolulu', 'Hilo', 'Kailua', 'Kaneohe', 'Waipahu'],
  id: ['Boise', 'Meridian', 'Nampa', 'Idaho Falls', 'Pocatello'],
  il: ['Chicago', 'Springfield', 'Peoria', 'Rockford', 'Champaign'],
  in: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel'],
  ia: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City', 'Iowa City'],
  ks: ['Wichita', 'Kansas City', 'Overland Park', 'Olathe', 'Topeka'],
  ky: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington'],
  la: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles'],
  me: ['Portland', 'Lewiston', 'Bangor', 'South Portland', 'Auburn'],
  md: ['Baltimore', 'Annapolis', 'Rockville', 'Gaithersburg', 'Frederick'],
  ma: ['Boston', 'Worcester', 'Springfield', 'Cambridge', 'Lowell'],
  mi: ['Detroit', 'Grand Rapids', 'Lansing', 'Ann Arbor', 'Flint'],
  mn: ['Minneapolis', 'St. Paul', 'Rochester', 'Duluth', 'Bloomington'],
  ms: ['Jackson', 'Gulfport', 'Southaven', 'Hattiesburg', 'Biloxi'],
  mo: ['Kansas City', 'St. Louis', 'Springfield', 'Columbia', 'Independence'],
  mt: ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Helena'],
  ne: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney'],
  nv: ['Las Vegas', 'Reno', 'Henderson', 'North Las Vegas', 'Sparks'],
  nh: ['Manchester', 'Nashua', 'Concord', 'Dover', 'Rochester'],
  nj: ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Trenton'],
  nm: ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe', 'Roswell'],
  ny: ['New York City', 'Buffalo', 'Rochester', 'Syracuse', 'Albany'],
  nc: ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem'],
  nd: ['Fargo', 'Bismarck', 'Grand Forks', 'Minot', 'West Fargo'],
  oh: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron'],
  ok: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Edmond'],
  or: ['Portland', 'Salem', 'Eugene', 'Gresham', 'Hillsboro'],
  pa: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading'],
  ri: ['Providence', 'Warwick', 'Cranston', 'Pawtucket', 'East Providence'],
  sc: ['Columbia', 'Charleston', 'North Charleston', 'Mount Pleasant', 'Rock Hill'],
  sd: ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings', 'Watertown'],
  tn: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville'],
  tx: ['Houston', 'Dallas', 'Austin', 'San Antonio', 'Fort Worth'],
  ut: ['Salt Lake City', 'West Valley City', 'Provo', 'West Jordan', 'Orem'],
  vt: ['Burlington', 'South Burlington', 'Rutland', 'Barre', 'Montpelier'],
  va: ['Virginia Beach', 'Norfolk', 'Chesapeake', 'Richmond', 'Newport News'],
  wa: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue'],
  wv: ['Charleston', 'Huntington', 'Parkersburg', 'Morgantown', 'Wheeling'],
  wi: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine'],
  wy: ['Cheyenne', 'Casper', 'Laramie', 'Gillette', 'Rock Springs'],
  // Territories
  dc: ['Washington'],
  pr: ['San Juan', 'Bayamón', 'Carolina', 'Ponce', 'Caguas'],
  gu: ['Hagåtña', 'Dededo', 'Yigo', 'Tamuning', 'Mangilao'],
  vi: ['Charlotte Amalie', 'Christiansted', 'Cruz Bay', 'Frederiksted'],
  mp: ['Saipan', 'Tinian', 'Rota'],
  as: ['Pago Pago', 'Nu\'uuli', 'Leone', 'Tafuna']
};