// Generated by Supabase CLI

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          full_name: string | null
          user_type: 'prose' | 'lawyer'
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          user_type: 'prose' | 'lawyer'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          user_type?: 'prose' | 'lawyer'
          created_at?: string
          updated_at?: string
        }
      }
      cases: {
        Row: {
          id: string
          title: string
          description: string
          type: 'civil' | 'family' | 'small_claims'
          status: 'open' | 'in_progress' | 'closed'
          client_id: string
          lawyer_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          description: string
          type: 'civil' | 'family' | 'small_claims'
          status?: 'open' | 'in_progress' | 'closed'
          client_id: string
          lawyer_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          description?: string
          type?: 'civil' | 'family' | 'small_claims'
          status?: 'open' | 'in_progress' | 'closed'
          client_id?: string
          lawyer_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
  }
}